Disable debug packages for Fedora 42 and below
The build still fails, errors seen:
```
[...]
Extracting debug info from 1 files
debugedit: /builddir/build/BUILD/tapir-edm-v0.0.0_20250922.bbd7f68-build/BUILDROOT/usr/bin/tapir-edm: Unsupported .debug_line directory 0 path DW_FORM_0x8
debugedit: /builddir/build/BUILD/tapir-edm-v0.0.0_20250922.bbd7f68-build/BUILDROOT/usr/bin/tapir-edm: Unsupported .debug_line directory 0 path DW_FORM_0x8
debugedit: /builddir/build/BUILD/tapir-edm-v0.0.0_20250922.bbd7f68-build/BUILDROOT/usr/bin/tapir-edm: Unsupported .debug_line directory 0 path DW_FORM_0x8
debugedit: /builddir/build/BUILD/tapir-edm-v0.0.0_20250922.bbd7f68-build/BUILDROOT/usr/bin/tapir-edm: Unsupported .debug_line directory 0 path DW_FORM_0x8
[...]
RPM build errors:
error: Empty %files file /builddir/build/BUILD/tapir-edm-v0.0.0_20250922.bbd7f68-build/tapir-edm/debugsourcefiles.list
    %source_date_epoch_from_changelog is set, but %changelog has no entries to take a date from
    Empty %files file /builddir/build/BUILD/tapir-edm-v0.0.0_20250922.bbd7f68-build/tapir-edm/debugsourcefiles.list
```

This might be related to go 1.25 enabling DWARF 5. That can be disabled
with GOEXPERIMENT=nodwarf5 but lets see if we can skip debug packags
to ignore this instead.