Disable debug packages on fedora 42 and newer (#124)
Build problem has appeared on fedora 43 similar to what has been seen on
fedora 42.

Change the rule to match "42 and newer" rather than the existing "42 and
older".

Some possibly related logging from build:
```
find-debuginfo: starting
Extracting debug info from 1 files
debugedit: /builddir/build/BUILD/dnstapir-edm-0.0.0_20251021.1f48a7a-build/BUILDROOT/usr/bin/dnstapir-edm: Unsupported .debug_line directory 0 path DW_FORM_0x8
debugedit: /builddir/build/BUILD/dnstapir-edm-0.0.0_20251021.1f48a7a-build/BUILDROOT/usr/bin/dnstapir-edm: Unsupported .debug_line directory 0 path DW_FORM_0x8
debugedit: /builddir/build/BUILD/dnstapir-edm-0.0.0_20251021.1f48a7a-build/BUILDROOT/usr/bin/dnstapir-edm: Unsupported .debug_line directory 0 path DW_FORM_0x8
debugedit: /builddir/build/BUILD/dnstapir-edm-0.0.0_20251021.1f48a7a-build/BUILDROOT/usr/bin/dnstapir-edm: Unsupported .debug_line directory 0 path DW_FORM_0x8
debugedit: /builddir/build/BUILD/dnstapir-edm-0.0.0_20251021.1f48a7a-build/BUILDROOT/usr/bin/dnstapir-edm: Unsupported .debug_line directory 0 path DW_FORM_0x8
debugedit: /builddir/build/BUILD/dnstapir-edm-0.0.0_20251021.1f48a7a-build/BUILDROOT/usr/bin/dnstapir-edm: Unsupported .debug_line directory 0 path DW_FORM_0x8
debugedit: /builddir/build/BUILD/dnstapir-edm-0.0.0_20251021.1f48a7a-build/BUILDROOT/usr/bin/dnstapir-edm: Unsupported .debug_line directory 0 path DW_FORM_0x8
debugedit: /builddir/build/BUILD/dnstapir-edm-0.0.0_20251021.1f48a7a-build/BUILDROOT/usr/bin/dnstapir-edm: Unsupported .debug_line directory 0 path DW_FORM_0x8
[...]
RPM build errors:
error: Empty %files file /builddir/build/BUILD/dnstapir-edm-0.0.0_20251021.1f48a7a-build/dnstapir-edm/debugsourcefiles.list
    %source_date_epoch_from_changelog is set, but %changelog has no entries to take a date from
    Empty %files file /builddir/build/BUILD/dnstapir-edm-0.0.0_20251021.1f48a7a-build/dnstapir-edm/debugsourcefiles.list
```